Unify GreeterWidget and SessionWidget
elementary/wingpanel-indicator-a11y pull request #20
Opened 2019-09-04 15:59 UTC by danrabbit

Keep things from diverging as we go by combining these two classes

2019-10-04 06:52 UTC, ryonakano commented
> It seems like we're getting a crash in the greeter because org.gnome.desktop.interface is not available in the greeter session

@danrabbit How did you face a crash? I don't see any problems with this branch and everything looks work as expected.

2021-04-23 16:31 UTC, jeremypw requested changes
Added some comments after looking at code - have not tried it out yet.

Tbh, I cannot immediately see why you need the `GLib.KeyFile` at all in the greeter session. It does not seem to be used for anything (?)

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +            warning (e.message);
Is it right to continue constructing the window if something when wrong with spawning the process?

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +            reader_pid = 0;
This repeats some code in the destructor

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +        keyboard_window.focus_on_map = false;
Does not use recommended code format for object construction.

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +    private KeyFile settings;
I would name this to indicate it is only used in a greeter session.

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +    private void toggle_screen_reader (bool active) {
I would name (or comment) this to indicate it is only called in a greeter session.  May add `requires settings != null`.

2021-04-23 16:31 UTC, jeremypw commented on src/SessionWidget.vala
> +                onscreen_keyboard.active = settings.get_boolean ("greeter", "onscreen-keyboard");
What is the point of this? You just set that setting to "false" a few lines back.  Can't you just set the keyboard switch to `off` directly, with out a try/catch clause?

2021-04-26 17:53 UTC, danrabbit commented
Hey sorry to waste your time on this @jeremypw. This should probably have been closed a long time ago or at least set as draft!

2022-05-14 16:55 UTC, closed without merging